spring.application.name=pedidos360-backend

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0e309e18-e3ab-4256-8fcf-5608cfe52cbe/v2.0
spring.security.oauth2.resourceserver.jwt.audiences[0]=c96eeade-7cad-46b0-979f-ca4e30aa8889
spring.security.oauth2.resourceserver.jwt.audiences[1]=api://c96eeade-7cad-46b0-979f-ca4e30aa8889

